auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8

title: Edward.com
url: http://Edward.com
feed: /atom.xml
author_info: <a href="http://www.liangye.info/">Edward</a>
